### ISSUE TITLE
Installing on Mac OSX

### ISSUE THREAD

**Issue by jhektor** [FABLE-3DXRD/ImageD11#104]
I'm trying to install on Mac OSX and are having some issues:
1. The compiler flags in setup.py are for the gcc compiler. The default C compiler in OSX is clang. I think I've solved this by installing gcc (from homebrew) and then building the code like this
```
CC="gcc-9" python setup.py build bdist_wheel
``` 
2. After installing the wheel I just built with
```
pip install dist/ImageD11-1.9.7-cp38-cp38-macosx_10_15_x86_64.whl
```
and trying to launch the gui I get the following error:
```
(base) hektor@Johans-jobb ImageD11 % conda activate fable
(fable) hektor@Johans-jobb ImageD11 % ImageD11_gui.py 
Traceback (most recent call last):
  File "/Users/hektor/opt/anaconda3/envs/fable/bin/ImageD11_gui.py", line 52, in <module>
    from ImageD11 import __version__, guicommand
  File "/Users/hektor/opt/anaconda3/envs/fable/lib/python3.8/site-packages/ImageD11/guicommand.py", line 33, in <module>
    from ImageD11 import peakmerge, indexing, transformer, eps_sig_solver
  File "/Users/hektor/opt/anaconda3/envs/fable/lib/python3.8/site-packages/ImageD11/indexing.py", line 24, in <module>
    from . import cImageD11, unitcell
  File "/Users/hektor/opt/anaconda3/envs/fable/lib/python3.8/site-packages/ImageD11/cImageD11.py", line 6, in <module>
    from ImageD11._cImageD11 import *
ImportError: dlopen(/Users/hektor/opt/anaconda3/envs/fable/lib/python3.8/site-packages/ImageD11/_cImageD11.cpython-38-darwin.so, 2): Symbol not found: _GOMP_loop_nonmonotonic_dynamic_next
  Referenced from: /Users/hektor/opt/anaconda3/envs/fable/lib/python3.8/site-packages/ImageD11/_cImageD11.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/hektor/opt/anaconda3/envs/fable/lib/python3.8/site-packages/ImageD11/_cImageD11.cpython-38-darwin.so
```
I suspect this is related to the build problem somehow but I don't know how to solve it. Any ideas?

**Comment by jonwright** [comment]
Can you try "cc=gcc-9 -fopenmp" and see if that fixes it? GOMP is the gnu openmp library. Theoretically clang should also take a -fopenmp: which arguments are causing a problem?
Thanks!

**Comment by jonwright** [comment]
I had a quick look using CC=clang on linux and it seems to build OK but there is a problem that it uses gcc to link instead of clang. This gives a similar missing symbol problem. If I manually link using clang then it appears to work here. Might be that it is compiling with gcc and linking with clang. This guy says openmp might be possible on mac these days:
https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

**Comment by jonwright** [comment]
So on linux I managed to find LDSHARED to get something that seems to work:
 
`CC="clang" LDSHARED="clang -shared" python  setup.py bdist_wheel`

So maybe if you add LDSHARED="gcc-9 -shared" it could start working? Let me know how you get on as there is an outstanding pull request to tidy up the mac build situation. Best would be to provide some binary wheels I guess?

**Comment by jhektor** [comment]
I think it is working now. I did the following
1. Installed OpenMP as suggested here: https://iscinumpy.gitlab.io/post/omp-on-high-sierra/ 
2. Added the ```-Xpreprocessor``` flag to the arg list in setup.py (not sure these two steps really helped anything)
3. Build like this ```CC="gcc-9" LDSHARED="gcc-9 -shared" LDFLAGS="-undefined dynamic_lookup" python setup.py bdist_wheel```
4. Installed like this ```CC="gcc-9" LDSHARED="gcc-9 -shared" LDFLAGS="-undefined dynamic_lookup" pip install -I dist/ImageD11-1.9.7-cp38-cp38-macosx_10_15_x86_64.whl```

I haven't tried doing anything, but at least the gui started. Thank you for looking into this.

**Comment by jonwright** [comment]
The undefined one makes me nervous it could segfault at runtime. Via Travis I managed to get an openmp disabled version running just now. If you can make a mac + openmp + travis recipe then I am happy to get a pull request. Reopen if #105 is not working for you please.
