### ISSUE TITLE
Forward projection

### ISSUE THREAD

**Issue by younes-elhachi** [FABLE-3DXRD/ImageD11#112]
- Update forward_project.py script: with the current version, peaks coordinates are outside the detector area ![cf. image](https://user-images.githubusercontent.com/27425753/87882614-6c5c7c80-ca01-11ea-9d69-656651f973e1.png).
- Future possibilities : make a UI above it (notebook, dashboard/plotly/bokeh, django web app?) to allow for visualisation & interactive info about peaks in each omega, compare to experimental/simulated images, etc.

**Comment by jonwright** [comment]
There is a little function 'inscan' in sandbox/forwards_project.py that was supposed to take care of this. The plot you show looks surprising.... how did you generate it?

**Comment by younes-elhachi** [comment]
I believe I was using an old version. It seems working nicely now.
![fwd_proj](https://user-images.githubusercontent.com/27425753/87988176-36da9080-cae0-11ea-8b2d-47a8967e7904.png)
