### ISSUE TITLE
Peaksearch incorrectly placing peaks

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#132]
Hello,

Not sure whether this is a bug or something I am doing wrong.
Below is a single frame powder diffraction image from our detector:
![image](https://user-images.githubusercontent.com/42615415/115687045-b20ff200-a351-11eb-9326-64801bbd051a.png)

Now, I use the following commands to generate peaks from it:
```
powderimagetopeaks.py input_image.cbf c0000.edf c0001.edf 730 680
peaksearch.py -n c -f 0 -l 1 -t 300 -t 600 -o ceo2.spt
```

Here's a quick look at c0000.edf:

![image](https://user-images.githubusercontent.com/42615415/115687491-234fa500-a352-11eb-95cd-93b7244fe62c.png)

It looks great!
However, when I plot the peaks in ImageD11:

![image](https://user-images.githubusercontent.com/42615415/115687626-48441800-a352-11eb-9e3a-c4f6c39484d2.png)

Am I doing something wrong?
To me, it looks like peaksearch isn't counting the module dead zones as actual regions of the image?

Any inputs welcome.

Thanks!

**Comment by jonwright** [comment]
It looks like it is finding a peak as a connected object that goes across a whole module. How high is the background level compared to your threshold levels?

**Comment by jadball** [comment]
Thanks, that has corrected most of the problems.
However, near thin module gaps, we are still getting incorrect peak position assignments:

![image](https://user-images.githubusercontent.com/42615415/115691111-a3c3d500-a355-11eb-83d1-aad52cb0c96c.png)

What do you think is the best way of cleaning them up?
Perhaps just masking to avoid them?

**Comment by jadball** [comment]
Here's another example in y/z for clarity:

![image](https://user-images.githubusercontent.com/42615415/115691705-33698380-a356-11eb-9346-02f3b67eb5a8.png)

**Comment by jonwright** [comment]
I think you are getting an incorrect position whenever a peak is connected to the mask?
e.g. `data_to_peaksearch = np.where( img == maskvalue, 10001, img)`
 
One option is to set the gap value to a high number (> threshold) and then everything will be connected to that mask object making a single 'peak'. You then just delete the one 'peak' which has a huge number of pixels.

The more recent dectris detectors are using gap values of (unsigned)(-1) which can make this happen semi-automatically.

**Comment by jadball** [comment]
Our gap values are all masked to -1 in the original .cbf files.
Is there a way to detect whether a peak is "connected" to any pixels with that value?
We'd rather not alter the original images.

**Comment by jonwright** [comment]
I think you would need to edit some code somewhere ?

The cleanest way to do this at the moment is probably via sandbox/hdfscan.py. It offers you a wrapper script that you can use to change numbers in place when reading data, also to remap new file formats etc.

Another option would be to edit ImageD11/correct.py to make the first line read as:
`data_object.data = data_object.data.view( np.uint32 )`

By casting to unsigned then (-1) becomes (2^32-1) and always above any threshold. At some later stage you would probably want to delete all peaks with IMax_int == (2^32-1). I guess this could be added as some new command line option. 

Alternatively you could load a mask, grow it by one pixel (scipy.ndimage.binary_dilate) and then try to figure out the intersections somewhere inside labelimage. 

In the longer term, I am try to stop using this peaksearch code and just save the "active" pixels into a sparse array. But that is not really finished yet.

**Comment by jonwright** [comment]
... maybe the grow-by-one mask approach could be useful and not all that bad to implement

**Comment by jadball** [comment]
Perfect! That seems to have worked very well.
I did the following:

Added `data_object.data = data_object.data.view( numpy.uint32 )` to the top of `correct.py`
Thresholded above highest recorded background
Processed resultant peaks file:
```
In [29]: peaks = columnfile("ceo2_t15000.flt")
In [30]: peaks.filter(peaks.IMax_int < 4294967294)
In [31]: print(peaks.IMax_int)
[32914. 51443. 15534. ... 15784. 15233. 16624.]
In [32]: print(peaks.IMax_int.max())
2221822.0
In [33]: peaks.writefile("filtered_15k.flt")
```

This looks very clean now:

![image](https://user-images.githubusercontent.com/42615415/115699693-ca860980-a35d-11eb-9e0b-47deac21ce49.png)

Many thanks for your help!
