### ISSUE TITLE
Peaksearch.py returns wrong omega values

### ISSUE THREAD

**Issue by siachilles** [FABLE-3DXRD/ImageD11#133]
Hi,

when using peaksearch.py on a series of diffraction patterns with an omega step size of 4 / 3 °, the resulting peaks.flt contains omega values which are not reasonable. E.g. peaks occur with omega values of 14.666666 °, but there is also one single peak with an omega value of 14.2796 °.

Going through peaksearcher.py I could locate that this altering of omega occurs in labelimage.py, when calling cImageD11.blob_moments. Just for completeness cImageD11.blob_moments is called in mergelast.

Is the altering of omega an intentional behaviour? I would expect no.

Best regards,
Silvio

**Comment by jonwright** [comment]
Hello,
The flt file gives the center of gravity for the peak in 3D over the image stack. You also have columns for the minimum and maximum omega (etc) for the bounding box of the peak in 3D. There are some dated notes here, I assumed you are looking at the "merged peaks":

https://imaged11.readthedocs.io/en/latest/fileformats.html

The 2D peaks that are on each individual frame without merging are in the spt files. These put the omega in the header block so it should be the same for all the peaks on a frame.

Feel free to re-open if something still does not seem right.

Best

Jon
