### ISSUE TITLE
h5py dependency is broken on windows 3.9

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/ImageD11#139]
... something about 2.10 ? Presumably due to the 32 bit problem for the CI

**Comment by szilviakalacska** [comment]
I found this useful: https://forum.hdfgroup.org/t/installation-of-old-version-of-h5py-2-10-0-fails/7995/2

**Comment by jonwright** [comment]
So this might be fixed by [#dd727fca](https://github.com/FABLE-3DXRD/ImageD11/pull/140/commits/dd727fca1b23b24770911ab1ea1244c6015eaab6)

I will leave this open for now as we miss binary wheels for python 3.6 -> 3.10 on windows...
