### ISSUE TITLE
Does `mageD11.indexing.indexer.score_all_pairs()` compute ring pairs twice?

### ISSUE THREAD

**Issue by AxelHenningsson** [FABLE-3DXRD/ImageD11#147]
This is a question about how one of the `ImageD11` indexing algorithms work.

**QUESTION**: 

Does [`mageD11.indexing.indexer.score_all_pairs()`](https://github.com/FABLE-3DXRD/ImageD11/blob/master/ImageD11/indexing.py) compute ring pairs twice?

e.g will `ring1` and `ring2` be computed for as well as `ring2` and `ring1`. What is the difference in outcome from these two computations. The cosine will be the same between peak pairs, so the same trials should be found?

It seems the answer is yes, but somehow different orientations are found in the end.

Best,
Axel

**Comment by jonwright** [comment]
It tries both ways around (r1,r2) as well as (r2,r1).

For each peak in r1, it takes the best matching peak in r2 (assuming cosine_tol is positive). If you make cosine_tol negative to try all pairs then I guess it will still be different on a second run. This is because peaks which are already indexed are supposed to get removed from the lists.

Are the orientations different because they are symmetry related or are they different because it is finding different ghosts ?

**Comment by AxelHenningsson** [comment]
Ok, I was surprised to why one needs to go (r1,r2) as well as (r2,r1)? Would it not be enough to just do unique permutations of rings and get a factor 2x speedup? I guess it should not find any "really new" (as in actually distinguishable) orientations just by flipping the ring order? Maybe I have a poor understanding somewhere..

**Comment by jonwright** [comment]
If there are 10 peaks in r1 and 100 peaks in r2 the you only get 10 trials for (r1,r2) but 100 for (r2,r1). The reason to test both is that right orientation may not be the pair with the best matching angle. If you test all pairs instead (negative cosine_tol) then you maybe be 10-100x slower ...

It depends on the number of grains. With a few grains it is fast anyway. With a lot of grains then it is better to do grid searches of orientation (e.g. grainspotter or fibre search).

**Comment by AxelHenningsson** [comment]
Ah, ok, thanks! For some reason I thought that for each r1 peak it would grab all r2 peaks that satisfied `cosine_tol`. But like you said above, it only grabs the best fit which _**also**_ satisfy  `cosine_tol`. Then it makes perfect sense that there will be new trials generated when looking at r1 to r2 compared to r2 to r1. Thanks!

**Comment by AxelHenningsson** [comment]
Closing this with the nice and clarifying answers provided by @jonwright.
