### ISSUE TITLE
Peak filtering method 

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#151]
This is a follow-on from #132

In my actual 3DXRD data, I'm still getting peaks that are poorly assigned if they are close to a module gap.

I've been able to generate a mask from our established detector mask at I12, so I have that array accessible.
I tried following your idea on filtering peaks based on whether they are close to a mask, using the min and max s and f values, but it doesn't seem to be doing much good, I'm still getting peaks close to module gaps that have incorrect positions:

```
import numpy as np
from ImageD11.columnfile import columnfile


def remove_max_int_peaks(input_flt_path, output_flt_path, mask):
    c = columnfile(input_flt_path)
    print(f"{c.nrows} peaks loaded")
    
    # Mask is a boolean array where bad pixels are True and good pixels are false

    # For each peak, take its range in s (Min_s, Max_s) and its range in f (Min_f, Max_f)
    # Crop the mask to that square
    # Look for any values of True in that square
    # If there are any, invalidate that peak

    bool_list = [mask[int(mins):int(maxs), int(minf):int(maxf)].any() for (mins, maxs, minf, maxf) in zip(c.Min_s, c.Max_s, c.Min_f, c.Max_f)]
    bool_list_as_filter = np.invert(bool_list)
    c.filter(bool_list_as_filter)

    print(f"{c.nrows} peaks survived")

    c.writefile(output_flt_path)
```

Is using Min_s, Max_s etc what you would recommend to do this?

![image](https://user-images.githubusercontent.com/42615415/167466725-1bb233ae-d8dc-4744-8e17-bd517d3179cb.png)

**Comment by jonwright** [comment]
I think the bounding box of the peak is always strictly within the module, assuming there are no bright pixels in the gaps? You probably just need to pad the box with (min-1) and (max+1) to find the peaks which are touching the edges. Let me know if something seems to be wrong with the bounding boxes (I guess that a box plot would be useful to verify).

**Comment by jadball** [comment]
Hi Jon,

Thank you very much, yes that suggestion worked perfectly with a mask dilated by 1 pixel.

For posterity, here's the full script I ended up with:

```python
import numpy as np
from ImageD11.columnfile import columnfile


def filter_peaks(input_flt_path, output_flt_path, mask):
    c = columnfile(input_flt_path)
    print(f"{c.nrows} peaks loaded")

    # Mask is a boolean array where bad pixels are True and good pixels are false
    # It's already been dilated by 1 pixel with scipy.ndimage.binary_dilation

    # Extract the bounding box of each peak (in pixels) using c.Min_s, c.Max_s, c.Min_f, c.Max_f
    # For each bounding box, crop the dilated mask to the bounding box
    # If any pixels in the cropped mask contain a 1 (a masked-out value), then that peak is too close to a masked pixel

    # bool_list = [mask[mins:maxs, minf:maxf].any() for (mins, maxs, minf, maxf) in zip(min_s, max_s, min_f, max_f)]

    bool_list = [mask[int(mins)-1:int(maxs)+1, int(minf)-1:int(maxf)+1].any() for (mins, maxs, minf, maxf) in zip(c.Min_s, c.Max_s, c.Min_f, c.Max_f)]

    bool_list_as_filter = np.invert(bool_list)
    c.filter(bool_list_as_filter)

    print(f"{c.nrows} peaks survived")

    c.writefile(output_flt_path)
```
