### ISSUE TITLE
`ImageD11.cImageD11` and `multiprocessing.Pool` does not perform as expected

### ISSUE THREAD

**Issue by AxelHenningsson** [FABLE-3DXRD/ImageD11#177]
Setting `OMP_NUM_THREADS=1` and running cImageD11 functions in parallel with python native multiprocessing module does not perform as expected . The runtime per call increases (🤔?!) with the number of processes when it should stay exactly constant  as it would be for any single threaded pure python function. For instance `cImageD11.cImageD11.score_and_assign()` performs as below on some dummy data.

![image](https://github.com/FABLE-3DXRD/ImageD11/assets/31615210/516d441e-6f06-4ce4-b275-4d7b29a7497b)

This is an issue when using ImageD11 for multi-grid indexing and various other more bizarre scanning-3dxrd applications. Perhaps there is a known trick to fix this, I know python native multiprocessing has been used a lot with ImageD11 so this should potentially be known? 🙃 

A self contained example below. (note that we are intentionally not measuring the Pool overhead of the forking and pickling-un-pickling) I have also tried to go `os.environ[OMP_NUM_THREADS]=1` with similar results. Similar things happens for other cImageD11 functions.

````python
import os
import numpy as np
import matplotlib.pyplot as plt
from multiprocessing import Pool
import ImageD11.cImageD11
from scipy.spatial.transform import Rotation
import ImageD11.grain
import time

def func(args):
    gve, grains, pin_omp_num_threads = args
    tol = 0.05
    drlv2 =  np.ones((gve.shape[1], ), 'd')
    label = -np.ones((gve.shape[1], ), 'i')
    if pin_omp_num_threads:
        ImageD11.cImageD11.cimaged11_omp_set_num_threads(1)
    t1 = time.perf_counter()
    for i, g in enumerate(grains):
            ImageD11.cImageD11.score_and_assign(g.ubi, gve.T, tol, drlv2, label, i)
    t2 = time.perf_counter()
    return (t2-t1)/len(grains)

if __name__ == "__main__":

    gve  = np.random.rand( 3, 100000 )
    grains = np.array([ImageD11.grain.grain(u) for u in Rotation.random(200).as_matrix()])

    plt.style.use('dark_background')
    plt.figure()
    for pin_omp_num_threads in [False, True]:
        time1core = func( (gve, grains, pin_omp_num_threads) )
        timings = [time1core]
        procs = [1]

        for nprocs in range(2, len(os.sched_getaffinity(0))):
            args = [(gve.copy(), gsub, pin_omp_num_threads) for gsub in np.array_split(grains.copy(), nprocs)]

            with Pool(processes=nprocs) as p:            
                runtimes = p.map( func, args )
            timings.append( np.mean(runtimes) )
            procs.append(nprocs)
            print(timings[-1])

        plt.plot(procs, timings, 'o--', label='pin OMP_NUM_THREADS : '+str(pin_omp_num_threads))
    plt.xlabel('Number of processes')
    plt.ylabel('Avg runtime [s/call] for ImageD11.cImageD11.score_and_assign()')
    plt.legend()
    plt.show()
````

**Comment by AxelHenningsson** [comment]
I am no thinking about trying to remove the "-fopenmp" flag in the setup.py and compile from source without openMP. [Seems OMP_NUM_THREADS=1 is problematic....](https://stackoverflow.com/questions/16635814/reasons-for-omp-set-num-threads1-slower-than-no-openmp)

**Comment by AxelHenningsson** [comment]
And there we go ... problem solved 😆 !  Variations down in the noise when compiling from source with
````python
````python
copt['unix'] = [ '-O2', ]
````
rather than 
````python
copt['unix'] = [ '-fopenmp', '-O2', ]
````
Perhaps this is related to the optimizer? Anyways, feels like something is wrong in OpenMP. If there is this much of overhead when not optimizing I rather it compile a single-threaded versions of the code and use this when OMP_NUM_THREADS=1.

![image](https://github.com/FABLE-3DXRD/ImageD11/assets/31615210/4244cc12-7690-4aea-b2d2-878d71e01b70)

**Comment by jonwright** [comment]
Hi Axel

I am testing python 3.10 on ubuntu with an AMD ryzen 5 5500U right now. At ESRF I don't remember seeing a problem with OMP_NUM_THREADS=1. So I guess you are on a mac, or some other unix? It would be good to track down the problem. There is also [threadpoolctl](https://github.com/joblib/threadpoolctl) that can help to fix these issues.

For your testcase - I can get it to run using spawn and forkserver, but not using fork. For now I did not figure out why, but something is deadlocking completely. I guess it is blowing up because we can't reset the threads after forking. The processes are sharing the same openmp runtime and so they can't both modify it - seems to be something that is not 'fork-safe'.

When it runs at all, if I run using OMP_NUM_THREADS=1 there is not much difference either way. If I do not, then oversubscription is a problem, and this is expected (nthreads*nprocs - in htop you see way too many threads running). If I compile without openmp there was not much change, maybe a bit slower, but I did not guess why.

Can you run with OMP_DISPLAY_ENV=True when you are trying to set OMP_NUM_THREADS=1? 

The numbers I see are:

```
OMP_NUM_THREADS=1 python3 ahtest.py 
Using startmethod forkserver
pin False
1 0.377ms;2 0.401ms;3 0.382ms;4 0.539ms;5 0.484ms;6 0.476ms;7 0.508ms;8 0.566ms;9 0.559ms;10 0.550ms;11 0.533ms;12 0.458ms;
pin True
1 0.391ms;2 0.381ms;3 0.380ms;4 0.386ms;5 0.493ms;6 0.479ms;7 0.410ms;8 0.540ms;9 0.549ms;10 0.529ms;11 0.552ms;12 0.432ms;


$ python3 ahtest.py   # e.g. threads is always set to 12.
Using startmethod forkserver
pin False
1 0.090ms;2 3.421ms;3 23.354ms;4 31.307ms;5 40.751ms;6 49.465ms;7 56.927ms;8 52.114ms;9 64.379ms;10 67.766ms;11 81.463ms;12 93.836ms;
pin True
1 0.391ms;2 0.513ms;3 0.554ms;4 0.476ms;5 0.458ms;6 0.407ms;7 0.518ms;8 0.721ms;9 0.898ms;10 1.698ms;11 1.458ms;12 0.950ms
```
Note that the best performance of all here was one process with 12 threads (0.090ms, the default option of compiling with -fopenmp and not using multiprocessing).


Code:
```
$ cat ahtest.py
import os
import numpy as np
import matplotlib.pyplot as plt
import multiprocessing
from multiprocessing import Pool
from scipy.spatial.transform import Rotation
import ImageD11.grain
import time, sys
import ImageD11.cImageD11
    
def func(args):
    gve, grains, pin_omp_num_threads = args
    tol = 0.05
    drlv2 =  np.ones((gve.shape[0], ), 'd')
    label = -np.ones((gve.shape[0], ), 'i')
    if pin_omp_num_threads:
        ImageD11.cImageD11.cimaged11_omp_set_num_threads(1)
    t1 = time.perf_counter()
    for i, g in enumerate(grains):
        ImageD11.cImageD11.score_and_assign(g, gve, tol, drlv2, label, i)
    t2 = time.perf_counter()
    return 1e3*(t2-t1)/len(grains)# ms

if __name__ == "__main__":
    multiprocessing.set_start_method('forkserver')
    print("Using startmethod",     multiprocessing.get_start_method())

    gve  = np.random.rand( 100000, 3 ) # cImageD11 expects them in memory like this
    grains = np.array([u for u in Rotation.random(200).as_matrix()])

    plt.style.use('dark_background')
    plt.figure()
    for pin_omp_num_threads in [False, True]:
        print('\npin',pin_omp_num_threads)
        time1core = func( (gve, grains, pin_omp_num_threads) )
        timings = [time1core]
        procs = [1]
        print(procs[-1], f'{timings[-1]:.3f}ms',end=';')
        for nprocs in range(2, len(os.sched_getaffinity(os.getpid()))+1):
            args = [(gve.copy(), gsub, pin_omp_num_threads) for gsub in np.array_split(grains.copy(), nprocs)]
            with Pool(processes=nprocs) as p:
                runtimes = p.map( func, args )
            timings.append( np.mean(runtimes) )
            procs.append(nprocs)
            print(procs[-1], f'{timings[-1]:.3f}ms',end=';')
        plt.plot(procs, timings, 'o--', label='pin OMP_NUM_THREADS : '+str(pin_omp_num_threads))
    plt.xlabel('Number of processes')
    plt.ylabel('Avg runtime [s/call] for ImageD11.cImageD11.score_and_assign()')
    plt.legend()
    plt.show()
```

**Comment by AxelHenningsson** [comment]
I am on our HCP cluster. A `cat /etc/*release` on the compute node gives me
````
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
````
`lscpu` gets me, among other things,
````
Model name:                      AMD EPYC 7413 24-Core Processor
Thread(s) per core:              1
````
I got `Python 3.11.5` in my active Anaconda 3 environment with `numpy 1.26.0`, `imaged11 2.0.0` and intel-`openmp 2023.1.0`.  

Running your - exact - script (using the `forkserver` option) the problem seem to be gone:
````
pin False
1 0.335ms;2 0.800ms;3 1.521ms;4 0.846ms;5 0.908ms;6 2.850ms;7 2.444ms;8 6.370ms;9 2.100ms;10 7.018ms;11 2.945ms;12 5.267ms;13 6.342ms;14 5.991ms;15 5.148ms;16 7.650ms;
pin True
1 0.380ms;2 0.577ms;3 0.659ms;4 0.641ms;5 1.134ms;6 0.725ms;7 0.855ms;8 1.080ms;9 0.915ms;10 0.709ms;11 1.304ms;12 0.756ms;13 0.808ms;14 0.895ms;15 0.902ms;
````
Going to `multiprocessing.set_start_method('fork')` the problem is back, as described in the original post:
````
pin False
1 0.479ms;2 0.481ms;3 0.659ms;4 0.754ms;5 1.261ms;6 1.081ms;7 1.892ms;8 1.838ms;9 2.276ms;10 2.583ms;11 2.992ms;12 2.948ms;13 3.839ms;14 4.263ms;15 5.721ms;16 6.409ms;
pin True
1 0.409ms;2 0.731ms;3 1.170ms;4 1.924ms;5 1.810ms;6 1.816ms;7 4.067ms;8 2.982ms;9 2.642ms;10 2.950ms;11 2.801ms;12 3.804ms;13 5.846ms;14 3.473ms;15 3.946ms;
````
(Can you actually not run at all using fork? That is weird?)
The `os.environ['OMP_DISPLAY_ENV']='True'` gives me:
````
OPENMP DISPLAY ENVIRONMENT BEGIN
  _OPENMP = '201511'
  OMP_DYNAMIC = 'FALSE'
  OMP_NESTED = 'FALSE'
  OMP_NUM_THREADS = '1'
  OMP_SCHEDULE = 'DYNAMIC'
  OMP_PROC_BIND = 'FALSE'
  OMP_PLACES = ''
  OMP_STACKSIZE = '0'
  OMP_WAIT_POLICY = 'PASSIVE'
  OMP_THREAD_LIMIT = '4294967295'
  OMP_MAX_ACTIVE_LEVELS = '1'
  OMP_CANCELLATION = 'FALSE'
  OMP_DEFAULT_DEVICE = '0'
  OMP_MAX_TASK_PRIORITY = '0'
  OMP_DISPLAY_AFFINITY = 'FALSE'
  OMP_AFFINITY_FORMAT = 'level %L thread %i affinity %A'
  OMP_ALLOCATOR = 'omp_default_mem_alloc'
  OMP_TARGET_OFFLOAD = 'DEFAULT'
OPENMP DISPLAY ENVIRONMENT END
````
Cheers
Axel

**Comment by AxelHenningsson** [comment]
I do not feel vey confident that we will make a lot more progress on this issue for now. I am happy I can compile without open mp for the time being. I suggest we close this issue unless you have some more thoughts on the root of the issue.

Cheers
Axel

**Comment by jonwright** [comment]
Hi Axel, 

From the python docs:

https://docs.python.org/3/library/multiprocessing.html

> Changed in version 3.12: If Python is able to detect that your process has multiple threads, the [os.fork()](https://docs.python.org/3/library/os.html#os.fork) function that this start method calls internally will raise a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning). Use a different start method. See the [os.fork()](https://docs.python.org/3/library/os.html#os.fork) documentation for further explanation.

https://docs.python.org/3/library/os.html#os.fork

>Changed in version 3.12: If Python is able to detect that your process has multiple threads, [os.fork()](https://docs.python.org/3/library/os.html#os.fork) now raises a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning).

>
>We chose to surface this as a warning, when detectable, to better inform developers of a design problem that the POSIX platform specifically notes as not supported. Even in code that appears to work, it has never been safe to mix threading with [os.fork()](https://docs.python.org/3/library/os.html#os.fork) on POSIX platforms. The CPython runtime itself has always made API calls that are not safe for use in the child process when threads existed in the parent (such as malloc and free).
>
>Users of macOS or users of libc or malloc implementations other than those typically found in glibc to date are among those already more likely to experience deadlocks running such code.
>
> See [this discussion on fork being incompatible with threads](https://discuss.python.org/t/33555) for technical details of why we’re surfacing this longstanding platform compatibility problem to developers.

**Comment by AxelHenningsson** [comment]
Aha, cool. Thanks, that explains quite  bit. :slightly_smiling_face:

**Comment by jonwright** [comment]
So I guess it is better to keep the issue open and figure something out. I guess intel creates a threadpool on loading and gomp does not. There is a related problem: It would make sense to try to figure out if we are running under multiprocessing and if so, set the number of threads to use as 1 to avoid the over subscription. This might be possible with:

Perhaps:

- during `import cImageD11`, check if it was compiled with openmp or not
- Only if we use openmp, then import multiprocessing and call `multiprocessing.get_start_method(allow_none=True)`

>If the start method has not been fixed and allow_none is false, then the start method is fixed to the default and the name is returned. If the start method has not been fixed and allow_none is true then None is returned.

Cases:

- None : we `set_default_startmethod` to forkserver or spawn, depending on `get_start_method(allow_none=False)`
- 'fork : we print a warning telling people their code is broken and linking https://discuss.python.org/t/33555 and this issue. And then continue running in case it works for them.

Check if this is a child process. If it finds a parent, call cimaged11_set_num_threads(1)
- `multiprocessing.parent_process()`: tells us we are a child process

Let me know if you spot a problem. I'll think about it for a bit more and then try to code + document something.
