### ISSUE TITLE
Fix + release for 3.12 when numba is ready

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/ImageD11#204]
When a new numba comes out : https://github.com/numba/numba/issues/9197

- fix setup.py to allow 3.12
- fix release.yml to build for 3.12
- fix the CI to test on 3.12

Longer term - make numba optional so we can still build/test everything that does not use it?

**Comment by jadball** [comment]
Numba is ready :)

Closed with PR #214
