### ISSUE TITLE
2D spot ID in 3D merge function

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#222]
Inside `sandbox/ma4750/custom_peak_search.py` we have the following function for 3D peak merging:

https://github.com/FABLE-3DXRD/ImageD11/blob/a8f80bbfda13150291f910f50bc989d41a2d3e7e/sandbox/ma4750/custom_peak_search.py#L14-L81

It would be nice to also keep track of the spot3d_id for each 2d peak, so we can follow the data back from grain -> 3d peaks -> 2d peaks -> raw data

**Comment by jonwright** [comment]
Isn't is just `spot3d_id` == `labels` in the code above?

**Comment by jadball** [comment]
Sorry, you're absolutely right! There's a nice way to verify by plotting the 2D merged peaks for a few 3D spots:
```
unique, counts = np.unique(cf_2d.spot3d_id, return_counts=True)
hits_dict = dict(zip(unique, counts))
hits_dict_max = sorted(hits_dict.items(), key=lambda x: x[1], reverse=True)

m = np.isin(cf_3d.index, [spot3d_id for spot3d_id, count in hits_dict_max[:10]])
cf_3d_single_peak = cf_3d.copy()
cf_3d_single_peak.filter(m)

peak_2d_mask = np.isin(cf_2d.spot3d_id, cf_3d_single_peak.index)
cf_2d_peaks = cf_2d.copy()
cf_2d_peaks.filter(peak_2d_mask)

fig, ax = plt.subplots()
ax.scatter(cf_3d_single_peak.f_raw, cf_3d_single_peak.s_raw, marker="X", c=cf_3d_single_peak.omega, label='Merged 3D peak')
cols = ax.scatter(cf_2d_peaks.f_raw, cf_2d_peaks.s_raw, c=cf_2d_peaks.o_raw, s=cf_2d_peaks.s_I / 1000, label='Contibutory 2D peaks')
fig.colorbar(cols)
ax.set_xlim(0, 2048)
ax.set_ylim(0, 2048)
ax.invert_yaxis()
ax.legend()
ax.set_title("Color is omega of peak. Scaled by sum intensity")
ax.set_xlabel("f_raw")
ax.set_ylabel("s_raw")
plt.show()
```

![image](https://github.com/FABLE-3DXRD/ImageD11/assets/42615415/df2ad8ec-273c-4d05-9787-484e9329ca1e)
