### ISSUE TITLE
add spatial + mask file paths to dataset (to clean up / simplify notebooks)

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/ImageD11#233]
Currently we have limapath, so only one limadetector? So have items like "dxfile + dyfile ,  splinefile, maskfile"

**Comment by jonwright** [comment]
This should allow us to have:
 dset -> load_pks2d (or 4d)

Using dset.pksfile and applying the spatial on loading

**Comment by jonwright** [comment]
Also the detector geometry parameter file!

So one dataset file is holding one detector + one sinogram.

The crystallographic phases and grains are probably not part of the dataset.

**Comment by jadball** [comment]
Related to this - the dataset object should have a method to automatically determine which mask and spatial files to use, given the detector serial number which we can get from the raw data h5 somewhere

**Comment by jadball** [comment]
Closing until we have mask and spatial files saved to the raw data H5.
