### ISSUE TITLE
Scale Eiger detector images to ring currents / fpico4 / fpico6 / something else

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#243]
From #242:

> The (fpico6, fpico4) monitor should be imported to the sparse files during assemble_label. We can add an option somewhere to use this in properties.py or add it to the peaks table (then normalise during pk2d or pk2dmerge).

**Comment by jonwright** [comment]
You can get the monitor via:
```
ds.pk2d['monitor'] = dataset.get_monitor_pk2d( ds.pk2d )
```
Then go ahead and use it. If we divide we mess up the statistics. If we carry the monitor around it becomes a scale factor for matching the observed and computed data later (without messing up statistics).
