### ISSUE TITLE
3DXRD/S3DXRD notebooks should contain no complicated functions

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#246]
The purpose of the notebooks should just be to choose the data to process and plot the results of that processing.
This will make creating workflows much easier.
This process should happen in two stages:

1. Move functions out of notebooks into nb_utils.

This ensures that the functions work from a standalone Python file

2. Move the functions from nb_utils into existing/new parts of ImageD11

**Comment by jadball** [comment]
#251 removed functions from notebooks

#257 worked out where the functions should go

Current task is to actually move them into ImageD11

**Comment by jadball** [comment]
@jonwright I have made some progress in distributing the functions into ImageD11 in my fork if you want to have a look:
https://github.com/jadball/ImageD11

However, it's still in progress so I wasn't planning on making a PR yet.
Do you anticipate any core changes to ImageD11 early next week? If so, I could submit a PR now to maintain linearity while i'm away next week.

**Comment by jonwright** [comment]
Just saw this - feel free to merge. I think I added something to speed up updateGeometry but there should be no conflicts.

**Comment by jadball** [comment]
Think this is now achieved
