### ISSUE TITLE
Python class for collection of grains

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#247]
We should have a Python class that handles collections of grains.
The underlying data structure can just be a list of grain objects (or, preferably, a `dict` of `{grain_id: grain_object}`)
The main feature needed to significantly simplify grain I/O between notebooks/workflow tasks is a class method to synchronise grain data to HDF5.
This should handle loading and saving to/from HDF5, and support things like additional grain attributes (above those defined by the `ImageD11.grain` class) such as per-grain sinograms and reconstructions.

**Comment by jonwright** [comment]
This collection could read/write to formats like pymicro or dream3d perhaps?

**Comment by jonwright** [comment]
Before I forget:
- a "grain" in ImageD11 is currently a single point representing a lattice (UBI -> strain, unit cell, orientation) and a centre of mass position (translation -> x,y,z)
- grains have no idea about their crystallographic phase, d-zero, and symmetry. The code should work for unknowns (P1) but maybe this can be a default that can override.
- for grain shape mapping: we need the "translation" to become arrays. Probably better in a some class and not a hack based on grain.translation.shape.
- for grain maps, there are many grains and we need a "split" and "merge" operation for low-angle boundaries
- We are missing the grain collection <-> peak collection sparse matrix too.

**Comment by jadball** [comment]
Should be handled in #253
