### ISSUE TITLE
GrainMap class

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#278]
We need a class to store information about a spatial map of a grain/multiple grains.
This class should do at least the following:

- [x] I/O to HDF5 group
- [x] Calculation of the following arrays:
    - [x] Grain ID - by combining recons from multiple different grains together
    - [x] Per-grain UBI - from grain objects
    - [x] Per-voxel UBI - by local refinement
    - [x] IPF X, Y, Z
    - [ ] Misorientation
    - [ ] Grain ID (segmentation from point-by-point data?)
    - [x] Phase ID?
 - [x] Creation methods:
    - [x] From a list of `GrainSinogram` objects
    - [x] Form the UBI array directly from point-by-point indexing

**Comment by jadball** [comment]
Mostly completed by #322 - per-voxel UBI by local refinement is ongoing, and I'm not sure we should be segmenting point-by-point data (leave as a task for MTEX?)

**Comment by jonwright** [comment]
About MTEX - the main problem seems to be output of multi-channel versus single channel results. Does MTEX allow several orientations per point together with a weight for each one?

**Comment by jadball** [comment]
No, as far as I am aware MTEX is single-valued. I have implemented a MTEX CTF export as a `TensorMap` classmethod.

**Comment by jadball** [comment]
Solved by #339

**Comment by jadball** [comment]
Closing
