### ISSUE TITLE
makemap.py introduces a rotation to grain positions in the lab frame for hexagonal systems

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#282]
While processing some recent DLS data (using latest ImageD11 stable from PyPI), I found an interesting discrepancy between our indexing for a cubic symmetry sample and a hexagonal symmetry sample.

For a cubic symmetry sample, the grain map and the tomography seem to match well:

![image](https://github.com/FABLE-3DXRD/ImageD11/assets/42615415/18d5c8ab-ccc3-4f0e-9144-826f34e0379c)

However, for a hexagonal symmetry sample, it appears that the grain map is rotated somehow:

![image](https://github.com/FABLE-3DXRD/ImageD11/assets/42615415/c580bf51-f1d3-4b0f-bf5b-1dbdc6f1d597)

Each of these grain maps were produced using `ImageD11.grid_index_parallel` from a merged `flt` file.

**Comment by jonwright** [comment]
How are you getting the omega angles for the diffraction scan? Does the tomo start/end at the same angles?

To look for an effect of symmetry in makemap, you can just turn it off and use P1 for everything. For now I don't have any idea why the symmetry would have any effect. The co-ordinate system comes from the angles that are input with the frames.
