### ISSUE TITLE
Multi-tensor map class

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#325]
We need a new class (or extend `PBPMap` from https://github.com/FABLE-3DXRD/ImageD11/blob/8c895dd4a54863a87b5692852afcb71e45d7d890/ImageD11/sinograms/point_by_point.py#L113) to handle point-by-point refinement.

The class needs to support the following conditions:

- [ ] Outer dimensions should be in reconstruction space (`ri`, `rj` like we use everywhere else)
- [ ] Support mixed-type, ragged-length arrays:
    - [ ] At each map pixel, we have variable-length `ubis`, `eps` and `npks` depending on how many grains we found at that point
- [ ] Not necessarily mutable (could make a new array for refinement results)
- [ ] IO support **essential** - we have to be able to save to disk
- [ ] Some `selbest` methods - for generating single-valued maps from multi-valued maps. A number of different methods could be used here.
- [ ] Generation from a `TensorMap` - results of tomographic refinement

From what I can see, `AwkwardArray` seems like a good way to start:
https://awkward-array.org/doc/main/getting-started/index.html

@jonwright what do you think?

**Comment by jadball** [comment]
I worry that having both a "SoA" carrying the raw data and an awkward array for row selections makes things very complicated. I think that the "SoA" approach could suffer a lot from slowdown when we are asking to get all the data at a specific grid point. Doing something like `grain_map[50, 30]` should always be pretty quick, and doing this as a columnfile would mean getting all the rows that match `i=50 & j=30` which I fear would be much slower.  Limiting the scope of our problem to a many-valued regular grid would simplify things a lot?

**Comment by jonwright** [comment]
The AoS vs SoA question is whether to store the columnfile table data by rows or by columns (e.g. doesn't matter on paper, depends on how computers work, etc). So long as the table rows are sorted by position in space then it can be fast/easy to index into them for both layouts.

With column storage, for the series of different arrays like UBI, UB, eps, sigma, etc, we should be able to share the "position in space indexing" pointers across all columns. Probably this can be done via any one of awkward/ragged/pydata_sparse_gcxs. Or we just have one array for each data item like  `UBI[ngrains, 3, 3]` and for each point in space we have the `start`, `len` indices to grab `UBI[ start[i,j] : start[i,j] + len[i:j] ]` (probably fails for `len == 0`). So in class PBPmap we would need to:

- ensure the data are grouped by position in space (no need to sort, but all grains from one position should be together)
- create an array `start[ nx, ny ]` with the first row for each position and also `len[nx, ny]`

Maybe the next thing to do is IO? The input (for now) is the output from PBPmap which is already columnfile. This would just add a couple of look up tables.

**Comment by jadball** [comment]
I think enforcing grouping gets tricky if we want to add a new UBI (or remove one) to/from an existing pixel? Otherwise I like this idea in theory. I think the thing to do is to try and write some refinement code, then probably the requirements we need/the most elegant approach will appear at some point...

**Comment by jadball** [comment]
Solved by #339 - we settled on a columnfile in the end, with `i, j, ubi00, ubi01` etc. entries. Seems to work well with minimal extra code needed.
