### ISSUE TITLE
Running out of memory when PBP indexing

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#340]
I'm now running out of memory when PBP indexing the SS316 dataset. I suspect that the issue is related to the new origin-of-diffraction correction I introduced into the PBP indexer:

https://github.com/FABLE-3DXRD/ImageD11/blob/47457f8a49a4e2c3457f46a14bc17c2ddae75717/ImageD11/sinograms/point_by_point.py#L1654-L1683

I think I'm running of out memory creating `tth, eta, gx, gy, gz`. What do we think the most efficient way is of correcting the origin of diffraction?

**Comment by jonwright** [comment]
Mask first (dtyi), then compute?

**Comment by jadball** [comment]
The problem is that we are determining `hkluniq` later on to score the UBIs found based on `peaks[m]`. I think I have a fix: https://github.com/FABLE-3DXRD/ImageD11/commit/36343d8cf898a0e490fff14f268f540b93028d5e
