### ISSUE TITLE
Issues resetting indexer when calling from wrapper script

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#88]
Hello,

I have written a "wrapper" python script to ImageD11, so that it can index multiple 3DXRD scans, one after the other.
For each scan, I am running the prepatory work (peaksearching, cleaning, merging etc), then calling a function which indexes the current scan.

My indexing function is as follows:

```
def init_index(gvecs, index_pars, outubis):
    """
    Performs initial index of g-vectors (same as "Auto-find" in ImageD11 gui)".
    """
    start = timer()
    myindexer.loadpars(index_pars)
    myindexer.readgvfile(gvecs)
    myindexer.score_all_pairs()
    myindexer.saveubis(outubis)
    myindexer.reset()
    end = timer()
    print("Initial index took ", (end - start)/60, " minutes.")
```

If I do not include a myindexer.reset() line, the number of grains found does not reset between scans.
For example, if I found 40 grains in my first scan, when I went to index the second scan, the number of grains found would _start_ at 40, then increase from there. I'd like each scan to be considered independent of the last.

I am having issues when trying to reset the indexer:

```
...
Tested 9 pairs and found 90 grains so far
Traceback (most recent call last):
  File "auto_single_letterbox.py", line 291, in <module>
    init_index(clean_gves, initial_index_pars, clean_ubis)
  File "auto_single_letterbox.py", line 118, in init_index
    myindexer.reset()
  File "/.../site-packages/ImageD11/indexing.py", line 319, in reset
    self.__dict__ = copy.deepcopy( self.__pristine_dict )
AttributeError: 'indexer' object has no attribute '_indexer__pristine_dict'
```

Any ideas?
Thanks in advance.

**Comment by jonwright** [comment]
You can just create myindexer as local to the function via `myindexer = indexing.indexer()`.
I guess the reset method is not setting __pristine_dict properly for the new object. I will try to see if I can fix it...

**Comment by jonwright** [comment]
Can you let me know if that fix doesn't work please? Thanks!

**Comment by jadball** [comment]
@jonwright Your fix does indeed work! Thanks for your help with this.
