### ISSUE TITLE
Cannot open files produced by powerimagetopeaks.py

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#98]
Hello,

I'm having problems with opening edf files generated with powderimagetopeaks.py
When I open the files with fabian.py or try to peaksearch them, I receive the following error message:

```
Traceback (most recent call last):
  File ".local/bin/fabian.py", line 33, in <module>
    start()
  File ".local/bin/fabian.py", line 28, in start
    mainwin = appWin.appWin(root,filename=f,zoomfactor=0.5,mainwin='yes')
  File ".local/lib/python2.7/site-packages/Fabian/appWin.py", line 1097, in __init__
    self.openimage()
  File ".local/lib/python2.7/site-packages/Fabian/appWin.py", line 1923, in openimage
    img = openimage.openimage(filename)
  File "anaconda/4.6.14/64/envs/python2.7/lib/python2.7/site-packages/fabio/openimage.py", line 159, in openimage
    obj = obj.read(obj.filename, frame)
  File "anaconda/4.6.14/64/envs/python2.7/lib/python2.7/site-packages/fabio/edfimage.py", line 788, in read
    raise e
IOError: Invalid first header
```

I do not have the same problem if I write another file format with powderimagetopeaks such as .CBF

**Comment by jonwright** [comment]
What is your fabio version? If you are on 10 then it might be worth checking if you get the same problem with 9:

pip install fabio==0.9.0

A lot of edf things were improved in the last release, so if you can check what version you have and upload an edf which cannot be opened I think we should fix it over at https://github.com/silx-kit/fabio/issues 

The code in powderimagetopeaks.py does not look like it does anything that would mess up a file format??

**Comment by jonwright** [comment]
A new fabio (v0.10.2) just went up on pypi. Can you see if that fixes it?

**Comment by jadball** [comment]
I'm afraid not, I'm building fabio directly from master at [https://github.com/silx-kit/fabio](https://github.com/silx-kit/fabio) and I still receive similar errors:

```
Traceback (most recent call last):
  File "/home/kuc84153/.local/lib/python3.7/site-packages/fabio/edfimage.py", line 1085, in _readheader
    value = self._read_header_block(infile, len(self._frames))
  File "/home/kuc84153/.local/lib/python3.7/site-packages/fabio/edfimage.py", line 900, in _read_header_block
    raise MalformedHeaderError("Header frame %i does not contain '{'" % frame_id)
fabio.edfimage.MalformedHeaderError: Header frame 0 does not contain '{'
```

I've uploaded an example edf image:
[EDF_zipped.zip](https://github.com/FABLE-3DXRD/ImageD11/files/4615058/EDF_zipped.zip)

**Comment by jonwright** [comment]
This is a cbf file, if you rename it to cbf you can read it. powderimagetopeaks is not changing file formats, it writes whatever it reads. Do you want it to convert instead? I would leave this to a separate program because whenever you convert formats you usually corrupt the headers.

**Comment by jadball** [comment]
Thanks for your explanation.
I was running the following command with the powderimagetopeaks script:
`powderimagetopeaks.py calibration_image.cbf c0000.edf c0001.edf 729 690`

I believe I had misunderstood the function of the script - I thought fabio was being used to write the output images.
I might raise a PR to add an extra print line to the program to warn that the image file format is not changed.
